from enum import Enum


class ErrorCode(str, Enum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    NOT_AUTHORIZED = "NOT_AUTHORIZED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    CONFLICT = "CONFLICT"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"

    # auth
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"

    # catalog
    DUPLICATE_SLUG = "DUPLICATE_SLUG"
    DUPLICATE_SKU = "DUPLICATE_SKU"
    PRODUCT_IN_USE = "PRODUCT_IN_USE"

    # orders
    EMPTY_CART = "EMPTY_CART"
    INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"
    PRODUCT_INACTIVE = "PRODUCT_INACTIVE"

    # admin panel additions
    SETUP_ALREADY_COMPLETED = "SETUP_ALREADY_COMPLETED"
    CANNOT_MODIFY_OWN_ACCOUNT = "CANNOT_MODIFY_OWN_ACCOUNT"
    CATEGORY_IN_USE = "CATEGORY_IN_USE"
    BRAND_IN_USE = "BRAND_IN_USE"
    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"

    # user invitation / password reset / audit log
    INVITATION_INVALID = "INVITATION_INVALID"
    INVITATION_EXPIRED = "INVITATION_EXPIRED"
    INVITATION_ALREADY_ACCEPTED = "INVITATION_ALREADY_ACCEPTED"
    RESET_TOKEN_INVALID = "RESET_TOKEN_INVALID"
    RESET_TOKEN_EXPIRED = "RESET_TOKEN_EXPIRED"
    INSUFFICIENT_ROLE_PRIVILEGE = "INSUFFICIENT_ROLE_PRIVILEGE"

    # checkout, addresses, payments & invoices
    INVALID_PAYMENT_METHOD = "INVALID_PAYMENT_METHOD"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_NOT_REFUNDABLE = "PAYMENT_NOT_REFUNDABLE"
    REFUND_EXCEEDS_PAYMENT_AMOUNT = "REFUND_EXCEEDS_PAYMENT_AMOUNT"
    INVOICE_NOT_AVAILABLE = "INVOICE_NOT_AVAILABLE"
