"""add addresses, payments, order status history, invoices

Revision ID: 6711e38c4d6f
Revises: 0fc312167c83
Create Date: 2026-07-05 17:47:10.466994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6711e38c4d6f'
down_revision: Union[str, Sequence[str], None] = '0fc312167c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('alternate_phone', sa.String(length=32), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.Column('postal_code', sa.String(length=32), nullable=False),
    sa.Column('delivery_instructions', sa.String(length=1000), nullable=True),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.Column('is_default_shipping', sa.Boolean(), nullable=False),
    sa.Column('is_default_billing', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('invoices',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_number')
    )
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=True)
    op.create_table('order_status_history',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('refunded_amount_cents', sa.Integer(), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    # NOTE: hand-edited -- autogenerate emitted a plain `nullable=False` add
    # here, which fails on a non-empty `order_items` table (existing rows
    # have no value to backfill from). Add with a temporary server_default
    # to backfill existing rows with an empty string, then drop the default
    # so it isn't relied on for new inserts (the app always supplies a real
    # sku_snapshot at checkout time).
    op.add_column(
        'order_items',
        sa.Column('sku_snapshot', sa.String(length=64), nullable=False, server_default=''),
    )
    op.alter_column('order_items', 'sku_snapshot', server_default=None)
    op.add_column('orders', sa.Column('shipping_address_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('billing_address_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_billing_address_id'), 'orders', ['billing_address_id'], unique=False)
    op.create_index(op.f('ix_orders_shipping_address_id'), 'orders', ['shipping_address_id'], unique=False)
    op.create_foreign_key(
        'fk_orders_shipping_address_id_addresses', 'orders', 'addresses',
        ['shipping_address_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_orders_billing_address_id_addresses', 'orders', 'addresses',
        ['billing_address_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: hand-edited -- autogenerate emitted unnamed
    # `op.drop_constraint(None, ...)` calls here, which fails at runtime
    # (there's no constraint named "None" to drop). The upgrade() side above
    # was likewise hand-edited to name these FKs explicitly so downgrade can
    # reference them.
    op.drop_constraint('fk_orders_billing_address_id_addresses', 'orders', type_='foreignkey')
    op.drop_constraint('fk_orders_shipping_address_id_addresses', 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_shipping_address_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_billing_address_id'), table_name='orders')
    op.drop_column('orders', 'billing_address_id')
    op.drop_column('orders', 'shipping_address_id')
    op.drop_column('order_items', 'sku_snapshot')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
