"""add gst tax fields to orders and gstin to addresses

Revision ID: cfc078fe82e1
Revises: 6711e38c4d6f
Create Date: 2026-07-05 18:11:44.444891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc078fe82e1'
down_revision: Union[str, Sequence[str], None] = '6711e38c4d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('gstin', sa.String(length=15), nullable=True))
    op.add_column('orders', sa.Column('taxable_amount_cents', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('cgst_cents', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('sgst_cents', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('igst_cents', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('tax_total_cents', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('grand_total_cents', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'grand_total_cents')
    op.drop_column('orders', 'tax_total_cents')
    op.drop_column('orders', 'igst_cents')
    op.drop_column('orders', 'sgst_cents')
    op.drop_column('orders', 'cgst_cents')
    op.drop_column('orders', 'taxable_amount_cents')
    op.drop_column('addresses', 'gstin')
    # ### end Alembic commands ###
